  hindi_lang = 
  {
    "Personal Details":"व्यक्तिगत विवरण",
	"Enter your name":"अपना नाम दर्ज करें *",
	"Enter your mobile number":"अपना मोबाइल नंबर दर्ज करें *",
	"Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"क्या आपके पास किसी भी अंतर्राष्ट्रीय यात्रा इतिहास / संपर्क इतिहास की पुष्टि सीओवीआईडी 19 मामले के साथ है? *",
	"No International Travel History/Contact History":"कोई अंतर्राष्ट्रीय यात्रा इतिहास / संपर्क इतिहास नहीं",
	"Travel History/Contact History more than 14 days":"यात्रा इतिहास / संपर्क इतिहास 14 दिन से अधिक",
	"Travel History/Contact History less than 14 days":"यात्रा इतिहास / संपर्क इतिहास 14 दिनों से कम",
	"Direct Contact with Confirmed COVID 19 case":"पुष्टि किए गए COVID 19 मामले के साथ सीधे संपर्क",
	"Body temperature/fever? *":"शरीर का तापमान / बुखार? *",
	"98.6 F to 100 F (36 C to 37.7 C)":"98.6 फ़ारेनहाइट से 100 फ़ारेनहाइट (36 सेल्सियस से 37.7 सेल्सियस)",
	"100 F to 102 F (36 C to 37.7 C)":"100 फ़ारेनहाइट से102 फ़ारेनहाइट (36 सेल्सियस से 37.7 सेल्सियस)",
	"102 F to 104 F (37.7 C to 40 C)":"102 फ़ारेनहाइट से 104 फ़ारेनहाइट (37.7 सेल्सियस से 40 सेल्सियस)",
	"more than 104 F (more than 40 C)":"104 फ़ारेनहाइट से अधिक(40 सेल्सियस से अधिक)",
	"Do you have any breathing difficulty? *":"क्या आपको सांस लेने में कोई कठिनाई है? *",
	"No":"नहीं",
	"Mild":"थोड़ा",
	"Moderate":"अधिक",
	"Severe":"गंभीर",
	"Do you have any pain in the body? *":"क्या आपको शरीर में कोई दर्द है? *",
	"Are you having any fatigue/weakness? *":"क्या आपको कोई थकान / कमजोरी है? *",
	"Do you have a sore throat? *":"क्या आपको खांसी है? *",
	"Do you have a cough? *":"क्या आपके गले में खराश है? *",
	"Do you have diarrhoea? *":"क्या आपको दस्त है? *",
	"No times in last 24 hrs":"पिछले 24 घंटे में नहीं",
	"1 to 3 times in last 24 hrs":"पिछले 24 घंटे में 1 से 3 बार",
	"4 to 7 times in last 24 hrs":"पिछले 24 घंटे में 4 से 7 बार",
	"More than 7 times in last 24 hrs":"पिछले 24 घंटे में 7 से अधिक बार",
	"Do you have any other medical conditions? *":"क्या आपको कोई अन्य चिकित्सा बीमारी है? *",
	"None":"कोई नहीं",
	"High BP":"हाई बी.पी.",
	"High BP + Diabetes Mellitus":"हाई बी.पी. + मधुमेह",
	"Reduced Immunity":"प्रतिरक्षा में कमी",
	"How is your health status in the last 48hrs? *":"पिछले 48 घंटों में आपकी स्वास्थ्य स्थिति कैसी है? *",
	"Improved":"हालत में सुधार",
	"No Change":"कोई परिवर्तन नहीं",
	"Worsened":"खराब हो गई है",
	"Worsened a lot":"बहुत खराब हो गई है",
	"Your age? *":"आपकी उम्र? *",
	"15 to 50 Yrs":"15 से 50 साल",
	"5 to 15 Yrs":"5 से 15 साल",
	"0 to 5 Yrs":"0 से 5 साल के",
	"More than 50 Yrs":"50 साल से अधिक",
	"Submit":"प्रस्तुत",
	"HOME":"घर",
	"You are safe, no need to worry":"आप सुरक्षित हैं, चिंता करने की कोई जरूरत नहीं है।",
	"Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"अत्यधिक सावधानी बरतें और घर पर रहें और स्थिति बिगड़ने पर चिकित्सा अधिकारियों को सूचित करें।",
	"Immediate medical attention is required and you may require COVID 19 testing":"तत्काल चिकित्सा ध्यान देने की आवश्यकता है और आपको COVID 19 परीक्षण की आवश्यकता हो सकती है।"
  };
  
  kannada_lang = 
  {
    "Personal Details":"ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
	"Enter your name":"ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ*",
	"Enter your mobile number":"ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರನ್ನು ನಮೂದಿಸಿರಿ*",
	"Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"ನೀವು ಯಾವುದೇ ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣ ಇತಿಹಾಸವನ್ನು ಹೊಂದಿದ್ದೀರಾ / ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಯಾವುದೇ ಸಂಪರ್ಕ ಇತಿಹಾಸವನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
	"No International Travel History/Contact History":"ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣದ ಇತಿಹಾಸವಿಲ್ಲ/ ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಸಂಪರ್ಕ ಇತಿಹಾಸವಿಲ್ಲ",
	"Travel History/Contact History more than 14 days":"ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣದ ಇತಿಹಾಸ/ ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಸಂಪರ್ಕ ಇತಿಹಾಸ 14 ದಿನಗಳಿಗಿಂತ ಹೆಚ್ಚು",
	"Travel History/Contact History less than 14 days":"ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣದ ಇತಿಹಾಸ/ ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಸಂಪರ್ಕ ಇತಿಹಾಸ 14 ದಿನಗಳಿಗಿಂತ ಕಡಿಮೆ",
	"Direct Contact with Confirmed COVID 19 case":"ಕೋವಿಡ್ 19 ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ನೇರ ಸಂಪರ್ಕ",
	"Body temperature/fever? *":"ದೇಹದ ಉಷ್ಣತೆ / ಜ್ವರ *",
	"98.6 F to 100 F (36 C to 37.7 C)":"98.6 ಫ್ಯಾರನ್ಹೀಟ್ ರಿಂದ 100 ಫ್ಯಾರನ್ಹೀಟ್ (36 ಸೆಲ್ಸಿಯಸ್ ರಿಂದ 37.7 ಸೆಲ್ಸಿಯಸ್)",
	"100 F to 102 F (36 C to 37.7 C)":"100 ಫ್ಯಾರನ್ಹೀಟ್ ರಿಂದ 102 ಫ್ಯಾರನ್ಹೀಟ್ (36 ಸೆಲ್ಸಿಯಸ್ ರಿಂದ 37.7 ಸೆಲ್ಸಿಯಸ್)",
	"102 F to 104 F (37.7 C to 40 C)":"102 ಫ್ಯಾರನ್ಹೀಟ್ ರಿಂದ 104 ಫ್ಯಾರನ್ಹೀಟ್ (37.7 ಸೆಲ್ಸಿಯಸ್ ರಿಂದ 40 ಸೆಲ್ಸಿಯಸ್)",
	"more than 104 F (more than 40 C)":"104 ಫ್ಯಾರನ್ಹೀಟ್ ಗಿಂತ ಹೆಚ್ಚು(40 ಸೆಲ್ಸಿಯಸ್ ಗಿಂತ ಹೆಚ್ಚು)",
	"Do you have any breathing difficulty? *":"ನಿಮಗೆ ಉಸಿರಾಟದ ತೊಂದರೆ ಇದೆಯೇ? *",
	"No":"ಇಲ್ಲ",
	"Mild":"ಸ್ವಲ್ಪ",
	"Moderate":"ಮಧ್ಯಮ",
	"Severe":"ತೀವ್ರ",
	"Do you have any pain in the body? *":"ನಿಮಗೆ ದೇಹದಲ್ಲಿ ಏನಾದರೂ ನೋವು ಇದೆಯೇ?*",
	"Are you having any fatigue/weakness? *":"ನೀವು ಯಾವುದೇ ಆಯಾಸ / ದೌರ್ಬಲ್ಯವನ್ನು ಹೊಂದಿದ್ದೀರಾ? *",
	"Do you have a sore throat? *":"ನಿಮಗೆ ಗಂಟಲು ನೋವು ಇದೆಯೇ? *",
	"Do you have a cough? *":"ನಿಮಗೆ ಕೆಮ್ಮು ಇದೆಯೇ? *",
	"Do you have diarrhoea? *":"ನಿಮಗೆ ಅತಿಸಾರ ಇದೆಯೇ? *",
	"No times in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ ಇಲ್ಲ",
	"1 to 3 times in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ ಇವುಗಳಲ್ಲಿ 1 ರಿಂದ 3 ಬಾರಿ",
	"4 to 7 times in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ ಇವುಗಳಲ್ಲಿ 4 ರಿಂದ 7 ಬಾರಿ",
	"More than 7 times in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ 7 ಕ್ಕೂ ಹೆಚ್ಚು ಬಾರಿ",
	"Do you have any other medical conditions? *":"ನೀವು ಬೇರೆ ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಹೊಂದಿದ್ದೀರಾ? *",
	"None":"ಯಾವುದೂ ಇಲ್ಲ",
	"High BP":"ಹೆಚ್ಚಿನ ಬಿಪಿ",
	"High BP + Diabetes Mellitus":"ಹೆಚ್ಚಿನ ಬಿಪಿ + ಮಧುಮೇಹ",
	"Reduced Immunity":"ರೋಗನಿರೋಧಕ ಶಕ್ತಿ ಕಡಿಮೆ ಇದೆ",
	"How is your health status in the last 48hrs? *":"ಕಳೆದ 48 ಗಂಟೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಆರೋಗ್ಯ ಸ್ಥಿತಿ ಹೇಗಿದೆ? *",
	"Improved":"ಸುಧಾರಿತ",
	"No Change":"ಬದಲಾವಣೆ ಇಲ್ಲ",
	"Worsened":"ಹದಗೆಟ್ಟಿದೆ",
	"Worsened a lot":"ಬಹಳಷ್ಟು ಹದಗೆಟ್ಟಿದೆ",
	"Your age? *":"ನಿಮ್ಮ ವಯಸ್ಸು? *",
	"15 to 50 Yrs":"15 ರಿಂದ 50 ವರ್ಷಗಳು",
	"5 to 15 Yrs":"5 ರಿಂದ 15 ವರ್ಷಗಳು",
	"0 to 5 Yrs":"0 ರಿಂದ 5 ವರ್ಷಗಳು",
	"More than 50 Yrs":"50 ವರ್ಷಕ್ಕಿಂತ ಹೆಚ್ಚು",
	"Submit":"ಸಲ್ಲಿಸು",
	"HOME":"ಮನೆ",
	"You are safe, no need to worry":"ನೀವು ಸುರಕ್ಷಿತ, ಚಿಂತಿಸಬೇಕಾಗಿಲ್ಲ",
	"Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"ತೀವ್ರ ಎಚ್ಚರಿಕೆ ವಹಿಸಿ ಮತ್ತು ಮನೆಯಲ್ಲಿಯೇ ಇರಿ ಮತ್ತು ಸ್ಥಿತಿ ಹದಗೆಟ್ಟರೆ ವೈದ್ಯಕೀಯ ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಿ",
	"Immediate medical attention is required and you may require COVID 19 testing":"ತಕ್ಷಣದ ವೈದ್ಯಕೀಯ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ ಮತ್ತು ನಿಮಗೆ COVID 19 ಪರೀಕ್ಷೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ"
  };
  
  telugu_lang = {"Personal Details":"వ్యక్తిగత వివరాలు","Enter your name":"మీ పేరును నమోదు చేయండి","Enter your mobile number":"మీ మొబైల్ నంబర్‌ను నమోదు చేయండి","Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"మీకు ధృవీకరించబడిన COVID 19 కేసుతో అంతర్జాతీయ ప్రయాణ చరిత్ర / సంప్రదింపు చరిత్ర ఉందా?","No International Travel History/Contact History":"అంతర్జాతీయ ప్రయాణ చరిత్ర / సంప్రదింపు చరిత్ర లేదు","Travel History/Contact History more than 14 days":"ప్రయాణం చరిత్ర / సంప్రదింపు చరిత్ర 14 రోజుల కన్నా ఎక్కువ ","Travel History/Contact History less than 14 days":" ప్రయాణ చరిత్ర / సంప్రదింపు చరిత్ర 14 రోజుల కన్నా తక్కువ ","Direct Contact with Confirmed COVID 19 case":" ధృవీకరించబడిన COVID 19 కేసుతో ప్రత్యక్ష పరిచయం ","Body temperature/fever? *":" శరీర ఉష్ణోగ్రత / జ్వరం? * ","98.6 F to 100 F (36 C to 37.7 C)":" 98.6 F నుండి 100 F (36 C to 37.7 C) ","100 F to 102 F (36 C to 37.7 C)":" 100 F నుండి 102 F (36 C నుండి 37.7 C) ","102 F to 104 F (37.7 C to 40 C)":" 102 F నుండి 104 F (37.7 C నుండి 40 C) ","more than 104 F (more than 40 C)":" 104 F కంటే ఎక్కువ (40 C కంటే ఎక్కువ) ","Do you have any breathing difficulty? *":" మీకు శ్వాస తీసుకోవడంలో ఏమైనా ఇబ్బంది ఉందా? * ","No":" లేదు ","Mild":" తేలికపాటి ","Moderate":" మితమైన ","Severe":" తీవ్రమైన ","Do you have any pain in the body? *":" మీకు శరీరంలో ఏదైనా నొప్పి ఉందా? * ","Are you having any fatigue/weakness? *":" మీకు ఏమైనా అలసట / బలహీనత ఉందా? * ","Do you have a sore throat? *":"మీకు గొంతు నొప్పి ఉందా? *","Do you have a cough? *":"మీకు దగ్గు ఉందా? *","Do you have diarrhoea? *":"మీకు విరేచనాలు ఉన్నాయా? *","No times in last 24 hrs":"గత 24 గంటలలో సార్లు లేవు","1 to 3 times in last 24 hrs":"చివరి 24 గంటలలో 1 నుండి 3 సార్లు","4 to 7 times in last 24 hrs":"గత 24 గంటల్లో 4 నుండి 7 సార్లు","More than 7 times in last 24 hrs":"గత 24 గంటలలో 7 సార్లు కంటే ఎక్కువ","Do you have any other medical conditions? *":"మీకు ఇతర వైద్య పరిస్థితులు ఉన్నాయా? *","None":"ఏదీ లేదు","High BP":"హై బిపి","High BP + Diabetes Mellitus":"హై బిపి + డయాబెటిస్ మెల్లిటస్ ","Reduced Immunity":" తగ్గిన రోగనిరోధక శక్తి ","How is your health status in the last 48hrs? *":" ఎలా ఉంది y గత 48 గంటల్లో మన ఆరోగ్య స్థితి? * ","Improved":" మెరుగైనది ","No Change":" మార్పు లేదు ","Worsened":" చెడ్డది ","Worsened a lot":" చాలా బాధపడ్డాడు ","Your age? *":" మీ వయస్సు? * ","15 to 50 Yrs":" 15 నుండి 50 సంవత్సరాలు ","5 to 15 Yrs":" 5 నుండి 15 సంవత్సరాలు ","0 to 5 Yrs":" 0 నుండి 5 సంవత్సరాలు ","More than 50 Yrs":" 50 ఏళ్ళకు పైగా ","Submit":" సమర్పించు ","HOME":" హోమ్ ","You are safe, no need to worry":" మీరు సురక్షితంగా ఉన్నారు, ఆందోళన చెందాల్సిన అవసరం లేదు ","Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"తీవ్ర జాగ్రత్త వహించండి మరియు ఇంట్లో ఉండండి మరియు పరిస్థితి క్షీణించినట్లయితే వైద్య అధికారులకు తెలియజేయండి","Immediate medical attention is required and you may require COVID 19 testing":"తక్షణ వైద్య సహాయం అవసరం మరియు మీకు COVID 19 పరీక్ష అవసరం కావచ్చు"};
  
  malayalam_lang = {"Personal Details":"വ്യക്തിഗത വിശദാംശങ്ങൾ","Enter your name":"നിങ്ങളുടെ പേര് നൽകുക","Enter your mobile number":"നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക","Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"സ്ഥിരീകരിച്ച COVID 19 കേസുമായി നിങ്ങൾക്ക് എന്തെങ്കിലും അന്താരാഷ്ട്ര യാത്രാ ചരിത്രം / ബന്ധപ്പെടാനുള്ള ചരിത്രം ഉണ്ടോ?","No International Travel History/Contact History":"അന്താരാഷ്ട്ര യാത്രാ ചരിത്രം / കോൺടാക്റ്റ് ചരിത്രം ഇല്ല","Travel History/Contact History more than 14 days":"യാത്ര ചരിത്രം / കോൺ‌ടാക്റ്റ് ചരിത്രം 14 ദിവസത്തിൽ കൂടുതൽ ","Travel History/Contact History less than 14 days":" യാത്രാ ചരിത്രം / കോൺ‌ടാക്റ്റ് ചരിത്രം 14 ദിവസത്തിൽ താഴെ ","Direct Contact with Confirmed COVID 19 case":" സ്ഥിരീകരിച്ച കോവിഡ് 19 കേസുമായി നേരിട്ടുള്ള സമ്പർക്കം ","Body temperature/fever? *":" ശരീര താപനില / പനി? * ","98.6 F to 100 F (36 C to 37.7 C)":" 98.6 എഫ് മുതൽ 100 ​​എഫ് വരെ (36 സി മുതൽ 37.7 സി വരെ ","100 F to 102 F (36 C to 37.7 C)":" 100 എഫ് മുതൽ 102 എഫ് വരെ (36 സി മുതൽ 37.7 സി വരെ) ","102 F to 104 F (37.7 C to 40 C)":" 102 എഫ് മുതൽ 104 എഫ് വരെ (37.7 സി മുതൽ 40 സി വരെ) ","more than 104 F (more than 40 C)":" 104 എഫ് (40 സിയിൽ കൂടുതൽ) ","Do you have any breathing difficulty? *":" നിങ്ങൾക്ക് ശ്വസിക്കാൻ ബുദ്ധിമുട്ടുണ്ടോ? * ","No":" ഇല്ല ","Mild":" മിതമായ ","Moderate":" മിതമായ ","Severe":" കഠിനമായ ","Do you have any pain in the body? *":" നിങ്ങൾക്ക് ശരീരത്തിൽ എന്തെങ്കിലും വേദനയുണ്ടോ? * ","Are you having any fatigue/weakness? *":" നിങ്ങൾക്ക് എന്തെങ്കിലും ക്ഷീണം / ബലഹീനത ഉണ്ടോ? * ","Do you have a sore throat? *":"നിങ്ങൾക്ക് തൊണ്ടവേദനയുണ്ടോ? *","Do you have a cough? *":"നിങ്ങൾക്ക് ചുമ ഉണ്ടോ? *","Do you have diarrhoea? *":"നിങ്ങൾക്ക് വയറിളക്കം ഉണ്ടോ? *","No times in last 24 hrs":"കഴിഞ്ഞ 24 മണിക്കൂറിനുള്ളിൽ സമയമില്ല","1 to 3 times in last 24 hrs":"കഴിഞ്ഞ 24 മണിക്കൂറിൽ 1 മുതൽ 3 തവണ വരെ","4 to 7 times in last 24 hrs":"കഴിഞ്ഞ 24 മണിക്കൂറിനുള്ളിൽ 4 മുതൽ 7 തവണ വരെ","More than 7 times in last 24 hrs":"കഴിഞ്ഞ 24 മണിക്കൂറിനുള്ളിൽ 7 തവണയിൽ കൂടുതൽ","Do you have any other medical conditions? *":"നിങ്ങൾക്ക് മറ്റ് മെഡിക്കൽ അവസ്ഥകളുണ്ടോ? *","None":"ഒന്നുമില്ല","High BP":"ഉയർന്ന ബിപി","High BP + Diabetes Mellitus":"ഉയർന്ന ബിപി + ഡയബറ്റിസ് മെലിറ്റസ് ","Reduced Immunity":" പ്രതിരോധശേഷി കുറച്ചു ","How is your health status in the last 48hrs? *":" എങ്ങനെ y കഴിഞ്ഞ 48 മണിക്കൂറിനുള്ളിൽ ഞങ്ങളുടെ ആരോഗ്യസ്ഥിതി? * ","Improved":" മെച്ചപ്പെടുത്തി ","No Change":" മാറ്റമില്ല ","Worsened":" മോശമായി ","Worsened a lot":" ഒരുപാട് മോശമായി ","Your age? *":" നിങ്ങളുടെ പ്രായം? * ","15 to 50 Yrs":" 15 മുതൽ 50 വർഷം വരെ ","5 to 15 Yrs":" 5 മുതൽ 15 വർഷം വരെ ","0 to 5 Yrs":" 0 മുതൽ 5 വർഷം വരെ ","More than 50 Yrs":" 50 വർഷത്തിൽ കൂടുതൽ ","Submit":" സമർപ്പിക്കുക ","HOME":" ഹോം ","You are safe, no need to worry":" നിങ്ങൾ സുരക്ഷിതരാണ്, വിഷമിക്കേണ്ടതില്ല ","Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"അതീവ ജാഗ്രത പാലിക്കുക, വീട്ടിൽ തന്നെ തുടരുക, അവസ്ഥ വഷളായാൽ മെഡിക്കൽ അധികാരികളെ അറിയിക്കുക","Immediate medical attention is required and you may require COVID 19 testing":"ഉടനടി വൈദ്യസഹായം ആവശ്യമാണ്, നിങ്ങൾക്ക് COVID 19 പരിശോധന ആവശ്യമായി വന്നേക്കാം"};
  
  marati_lang = {"Personal Details":"वैयक्तिक तपशील","Enter your name":"आपले नाव प्रविष्ट करा","Enter your mobile number":"आपला मोबाइल नंबर प्रविष्ट करा","Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"आपल्याकडे पुष्टीकृत कोविड 19 प्रकरणातील कोणताही आंतरराष्ट्रीय प्रवास इतिहास / संपर्क इतिहास आहे?","No International Travel History/Contact History":"आंतरराष्ट्रीय प्रवास इतिहास / संपर्क इतिहास नाही","Travel History/Contact History more than 14 days":"प्रवास इतिहास / संपर्क इतिहास 14 दिवसांपेक्षा जास्त ","Travel History/Contact History less than 14 days":" प्रवासाचा इतिहास / 14 दिवसांपेक्षा कमी कालावधीचा संपर्क इतिहास ","Direct Contact with Confirmed COVID 19 case":" कन्फर्म्ड कोविड 19 प्रकरणाचा थेट संपर्क ","Body temperature/fever? *":" शरीराचे तापमान / ताप? * ","98.6 F to 100 F (36 C to 37.7 C)":" 98.6 फॅ ते 100 फॅ (36 से. ते 37.7 सी) ","100 F to 102 F (36 C to 37.7 C)":" 100 फॅ ते १०२ फॅ (C 36 से ते .7 37. C से) ","102 F to 104 F (37.7 C to 40 C)":"१०२ फॅ ते १०4 फॅ (.7 37. C से ते C० से) पर्यंत","more than 104 F (more than 40 C)":"१०4 फॅ पेक्षा जास्त (C० से अधिक सेल्सियस)","Do you have any breathing difficulty? *":" तुम्हाला श्वासोच्छवासाची अडचण आहे? * ","No":" नाही ","Mild":" सौम्य ","Moderate":" मध्यम ","Severe":" गंभीर ","Do you have any pain in the body? *":" तुमच्या शरीरात काही वेदना आहे का? * ","Are you having any fatigue/weakness? *":" तुम्हाला थकवा / अशक्तपणा आहे? * ","Do you have a sore throat? *":"तुम्हाला घसा खवखवतो आहे काय? *","Do you have a cough? *":"तुम्हाला खोकला आहे का? *","Do you have diarrhoea? *":"आपल्याला अतिसार आहे? *","No times in last 24 hrs":"गेल्या 24 तासांत कधीच वेळ नाही","1 to 3 times in last 24 hrs":"गेल्या 24 तासात 1 ते 3 वेळा","4 to 7 times in last 24 hrs":"गेल्या 24 तासात 4 ते 7 वेळा","More than 7 times in last 24 hrs":"गेल्या 24 तासात 7 वेळापेक्षा जास्त वेळा","Do you have any other medical conditions? *":"आपल्याकडे इतर काही वैद्यकीय परिस्थिती आहे का? *","None":"काहीही नाही","High BP":"हाय बीपी","High BP + Diabetes Mellitus":"हाय बीपी + डायबेटिस मेलिटस ","Reduced Immunity":" प्रतिकारशक्ती कमी केली ","How is your health status in the last 48hrs? *":" y कसे आहे गेल्या 48 तासात आपली आरोग्य स्थिती? * ","Improved":" सुधारित ","No Change":" बदल नाही ","Worsened":" खराब झाले ","Worsened a lot":" बर्‍याच वेळा खराब झाले ","Your age? *":" आपले वय? * ","15 to 50 Yrs":" 15 ते 50 वर्ष ","5 to 15 Yrs":" 5 ते 15 वर्ष ","0 to 5 Yrs":" 0 ते 5 वर्ष ","More than 50 Yrs":" 50 वर्षांपेक्षा जास्त ","Submit":" सबमिट करा ","HOME":" घर ","You are safe, no need to worry":" आपण सुरक्षित आहात, काळजी करण्याची गरज नाही ","Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"अत्यंत सावधगिरी बाळगा आणि घरीच राहा आणि परिस्थिती बिघडल्यास वैद्यकीय अधिका not्यांना सूचित करा","Immediate medical attention is required and you may require COVID 19 testing":"त्वरित वैद्यकीय मदत घेणे आवश्यक आहे आणि आपणास कोविड १ testing चाचणीची आवश्यकता असू शकते"};
  
  tamil_lang = {"Personal Details":"தனிப்பட்ட விவரங்கள்","Enter your name":"உங்கள் பெயரை உள்ளிடுக","Enter your mobile number":"உங்கள் மொபைல் எண்ணை உள்ளிடுக","Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"உறுதிப்படுத்தப்பட்ட COVID 19 வழக்கில் உங்களுக்கு ஏதேனும் சர்வதேச பயண வரலாறு / தொடர்பு வரலாறு உள்ளதா?","No International Travel History/Contact History":"சர்வதேச பயண வரலாறு / தொடர்பு வரலாறு இல்லை","Travel History/Contact History more than 14 days":"பயணம் வரலாறு / தொடர்பு வரலாறு 14 நாட்களுக்கு மேல் ","Travel History/Contact History less than 14 days":" பயண வரலாறு / தொடர்பு வரலாறு 14 நாட்களுக்கு குறைவாக ","Direct Contact with Confirmed COVID 19 case":" உறுதிப்படுத்தப்பட்ட கோவிட் 19 வழக்குடன் நேரடி தொடர்பு ","Body temperature/fever? *":" உடல் வெப்பநிலை / காய்ச்சல்? * ","98.6 F to 100 F (36 C to 37.7 C)":" 98.6 எஃப் முதல் 100 எஃப் (36 சி to 37.7 சி) ","100 F to 102 F (36 C to 37.7 C)":" 100 எஃப் முதல் 102 எஃப் (36 சி முதல் 37.7 சி) ","102 F to 104 F (37.7 C to 40 C)":" 102 எஃப் முதல் 104 எஃப் (37.7 சி முதல் 40 சி) ","more than 104 F (more than 40 C)":" 104 எஃப் க்கு மேல் (40 சி க்கு மேல்) ","Do you have any breathing difficulty? *":" உங்களுக்கு சுவாசிக்க சிரமம் உள்ளதா? * ","No":" இல்லை ","Mild":" லேசான ","Moderate":" மிதமான ","Severe":" கடுமையான ","Do you have any pain in the body? *":" உங்களுக்கு உடலில் ஏதேனும் வலி இருக்கிறதா? * ","Are you having any fatigue/weakness? *":" உங்களுக்கு ஏதேனும் சோர்வு / பலவீனம் இருக்கிறதா? * ","Do you have a sore throat? *":"உங்களுக்கு தொண்டை வலி இருக்கிறதா? *","Do you have a cough? *":"உங்களுக்கு இருமல் இருக்கிறதா? *","Do you have diarrhoea? *":"உங்களுக்கு வயிற்றுப்போக்கு இருக்கிறதா? *","No times in last 24 hrs":"கடந்த 24 மணி நேரத்தில் நேரங்கள் இல்லை","1 to 3 times in last 24 hrs":"கடந்த 24 மணி நேரத்தில் 1 முதல் 3 முறை","4 to 7 times in last 24 hrs":"கடந்த 24 மணி நேரத்தில் 4 முதல் 7 முறை","More than 7 times in last 24 hrs":"கடந்த 24 மணி நேரத்தில் 7 முறைக்கு மேல்","Do you have any other medical conditions? *":"உங்களுக்கு வேறு மருத்துவ நிலைமைகள் உள்ளதா? *","None":"எதுவுமில்லை","High BP":"உயர் பிபி","High BP + Diabetes Mellitus":"உயர் பிபி + நீரிழிவு நோய் ","Reduced Immunity":" குறைக்கப்பட்ட நோய் எதிர்ப்பு சக்தி ","How is your health status in the last 48hrs? *":" எப்படி y கடந்த 48 மணிநேரத்தில் எங்கள் சுகாதார நிலை? * ","Improved":" மேம்படுத்தப்பட்டது ","No Change":" மாற்றம் இல்லை ","Worsened":" மோசமாகிவிட்டது ","Worsened a lot":" நிறைய மோசமாகிவிட்டது ","Your age? *":" உங்கள் வயது? * ","15 to 50 Yrs":" 15 முதல் 50 ஆண்டுகள் ","5 to 15 Yrs":" 5 முதல் 15 ஆண்டுகள் ","0 to 5 Yrs":" 0 முதல் 5 ஆண்டுகள் ","More than 50 Yrs":" 50 வயதிற்கு மேல் ","Submit":" சமர்ப்பி ","HOME":" வீடு ","You are safe, no need to worry":" நீங்கள் பாதுகாப்பாக இருக்கிறீர்கள், கவலைப்பட தேவையில்லை ","Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"தீவிர எச்சரிக்கையுடன் உடற்பயிற்சி செய்து வீட்டிலேயே இருங்கள் மற்றும் நிலை மோசமடைந்துவிட்டால் மருத்துவ அதிகாரிகளுக்கு அறிவிக்கவும்","Immediate medical attention is required and you may require COVID 19 testing":"உடனடி மருத்துவ கவனிப்பு தேவை, உங்களுக்கு COVID 19 சோதனை தேவைப்படலாம்"};