  hindi_lang = 
  {
    "Personal Details":"व्यक्तिगत विवरण",
	"Enter your name":"अपना नाम दर्ज करें *",
	"Enter your mobile number":"अपना मोबाइल नंबर दर्ज करें *",
	"Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"क्या आपके पास किसी भी अंतर्राष्ट्रीय यात्रा इतिहास / संपर्क इतिहास की पुष्टि सीओवीआईडी 19 मामले के साथ है? *",
	"No International Travel History/Contact History":"कोई अंतर्राष्ट्रीय यात्रा इतिहास / संपर्क इतिहास नहीं",
	"Travel History/Contact History more than 14 days":"यात्रा इतिहास / संपर्क इतिहास 14 दिन से अधिक",
	"Travel History/Contact History less than 14 days":"यात्रा इतिहास / संपर्क इतिहास 14 दिनों से कम",
	"Direct Contact with Confirmed COVID 19 case":"पुष्टि किए गए COVID 19 मामले के साथ सीधे संपर्क",
	"Body temperature/fever? *":"शरीर का तापमान / बुखार? *",
	"98.6 F to 100 F (36 C to 37.7 C)":"98.6 फ़ारेनहाइट से 100 फ़ारेनहाइट (36 सेल्सियस से 37.7 सेल्सियस)",
	"100 F to 102 F (36 C to 37.7 C)":"100 फ़ारेनहाइट से102 फ़ारेनहाइट (36 सेल्सियस से 37.7 सेल्सियस)",
	"102 F to 104 F (37.7 C to 40 C)":"102 फ़ारेनहाइट से 104 फ़ारेनहाइट (37.7 सेल्सियस से 40 सेल्सियस)",
	"more than 104 F (more than 40 C)":"104 फ़ारेनहाइट से अधिक(40 सेल्सियस से अधिक)",
	"Do you have any breathing difficulty? *":"क्या आपको सांस लेने में कोई कठिनाई है? *",
	"No":"नहीं",
	"Mild":"थोड़ा",
	"Moderate":"अधिक",
	"Severe":"गंभीर",
	"Do you have any pain in the body? *":"क्या आपको शरीर में कोई दर्द है? *",
	"Are you having any fatigue/weakness? *":"क्या आपको कोई थकान / कमजोरी है? *",
	"Do you have a sore throat? *":"क्या आपको खांसी है? *",
	"Do you have a cough? *":"क्या आपके गले में खराश है? *",
	"Do you have diarrhoea? *":"क्या आपको दस्त है? *",
	"No episodes in last 24 hrs":"पिछले 24 घंटे में नहीं",
	"1 to 3 episodes in last 24 hrs":"पिछले 24 घंटे में 1 से 3 बार",
	"4 to 7 episodes in last 24 hrs":"पिछले 24 घंटे में 4 से 7 बार",
	"More than 7 episodes in last 24 hrs":"पिछले 24 घंटे में 7 से अधिक बार",
	"Do you have any other medical conditions? *":"क्या आपको कोई अन्य चिकित्सा बीमारी है? *",
	"None":"कोई नहीं",
	"High BP":"हाई बी.पी.",
	"High BP + Diabetes Mellitus":"हाई बी.पी. + मधुमेह",
	"Reduced Immunity":"प्रतिरक्षा में कमी",
	"How is your health status in the last 48hrs? *":"पिछले 48 घंटों में आपकी स्वास्थ्य स्थिति कैसी है? *",
	"Improved":"हालत में सुधार",
	"No Change":"कोई परिवर्तन नहीं",
	"Worsened":"खराब हो गई है",
	"Worsened a lot":"बहुत खराब हो गई है",
	"Your age? *":"आपकी उम्र? *",
	"15 to 50 Yrs":"15 से 50 साल",
	"5 to 15 Yrs":"5 से 15 साल",
	"0 to 5 Yrs":"0 से 5 साल के",
	"More than 50 Yrs":"50 साल से अधिक",
	"Submit":"प्रस्तुत",
	"HOME":"घर",
	"You are safe, no need to worry":"आप सुरक्षित हैं, चिंता करने की कोई जरूरत नहीं है।",
	"Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"अत्यधिक सावधानी बरतें और घर पर रहें और स्थिति बिगड़ने पर चिकित्सा अधिकारियों को सूचित करें।",
	"Immediate medical attention is required and you may require COVID 19 testing":"तत्काल चिकित्सा ध्यान देने की आवश्यकता है और आपको COVID 19 परीक्षण की आवश्यकता हो सकती है।"
  };
  
  kan_lang = 
  {
    "Personal Details":"ವೈಯಕ್ತಿಕ ವಿವರಗಳು",
	"Enter your name":"ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ*",
	"Enter your mobile number":"ನಿಮ್ಮ ಮೊಬೈಲ್ ನಂಬರನ್ನು ನಮೂದಿಸಿರಿ*",
	"Do you have any International Travel History/Contact History with Confirmed COVID 19 case?":"ನೀವು ಯಾವುದೇ ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣ ಇತಿಹಾಸವನ್ನು ಹೊಂದಿದ್ದೀರಾ / ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಯಾವುದೇ ಸಂಪರ್ಕ ಇತಿಹಾಸವನ್ನು ಹೊಂದಿದ್ದೀರಾ?",
	"No International Travel History/Contact History":"ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣದ ಇತಿಹಾಸವಿಲ್ಲ/ ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಸಂಪರ್ಕ ಇತಿಹಾಸವಿಲ್ಲ",
	"Travel History/Contact History more than 14 days":"ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣದ ಇತಿಹಾಸ/ ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಸಂಪರ್ಕ ಇತಿಹಾಸ 14 ದಿನಗಳಿಗಿಂತ ಹೆಚ್ಚು",
	"Travel History/Contact History less than 14 days":"ಅಂತರರಾಷ್ಟ್ರೀಯ ಪ್ರಯಾಣದ ಇತಿಹಾಸ/ ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ಸಂಪರ್ಕ ಇತಿಹಾಸ 14 ದಿನಗಳಿಗಿಂತ ಕಡಿಮೆ",
	"Direct Contact with Confirmed COVID 19 case":"ಕೋವಿಡ್ 19 ದೃಡೀಕರಿಸಿದ ಪ್ರಕರಣದೊಂದಿಗೆ ನೇರ ಸಂಪರ್ಕ",
	"Body temperature/fever? *":"ದೇಹದ ಉಷ್ಣತೆ / ಜ್ವರ *",
	"98.6 F to 100 F (36 C to 37.7 C)":"98.6 ಫ್ಯಾರನ್ಹೀಟ್ ರಿಂದ 100 ಫ್ಯಾರನ್ಹೀಟ್ (36 ಸೆಲ್ಸಿಯಸ್ ರಿಂದ 37.7 ಸೆಲ್ಸಿಯಸ್)",
	"100 F to 102 F (36 C to 37.7 C)":"100 ಫ್ಯಾರನ್ಹೀಟ್ ರಿಂದ 102 ಫ್ಯಾರನ್ಹೀಟ್ (36 ಸೆಲ್ಸಿಯಸ್ ರಿಂದ 37.7 ಸೆಲ್ಸಿಯಸ್)",
	"102 F to 104 F (37.7 C to 40 C)":"102 ಫ್ಯಾರನ್ಹೀಟ್ ರಿಂದ 104 ಫ್ಯಾರನ್ಹೀಟ್ (37.7 ಸೆಲ್ಸಿಯಸ್ ರಿಂದ 40 ಸೆಲ್ಸಿಯಸ್)",
	"more than 104 F (more than 40 C)":"104 ಫ್ಯಾರನ್ಹೀಟ್ ಗಿಂತ ಹೆಚ್ಚು(40 ಸೆಲ್ಸಿಯಸ್ ಗಿಂತ ಹೆಚ್ಚು)",
	"Do you have any breathing difficulty? *":"ನಿಮಗೆ ಉಸಿರಾಟದ ತೊಂದರೆ ಇದೆಯೇ? *",
	"No":"ಇಲ್ಲ",
	"Mild":"ಸ್ವಲ್ಪ",
	"Moderate":"ಮಧ್ಯಮ",
	"Severe":"ತೀವ್ರ",
	"Do you have any pain in the body? *":"ನಿಮಗೆ ದೇಹದಲ್ಲಿ ಏನಾದರೂ ನೋವು ಇದೆಯೇ?*",
	"Are you having any fatigue/weakness? *":"ನೀವು ಯಾವುದೇ ಆಯಾಸ / ದೌರ್ಬಲ್ಯವನ್ನು ಹೊಂದಿದ್ದೀರಾ? *",
	"Do you have a sore throat? *":"ನಿಮಗೆ ಗಂಟಲು ನೋವು ಇದೆಯೇ? *",
	"Do you have a cough? *":"ನಿಮಗೆ ಕೆಮ್ಮು ಇದೆಯೇ? *",
	"Do you have diarrhoea? *":"ನಿಮಗೆ ಅತಿಸಾರ ಇದೆಯೇ? *",
	"No episodes in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ ಇಲ್ಲ",
	"1 to 3 episodes in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ ಇವುಗಳಲ್ಲಿ 1 ರಿಂದ 3 ಬಾರಿ",
	"4 to 7 episodes in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ ಇವುಗಳಲ್ಲಿ 4 ರಿಂದ 7 ಬಾರಿ",
	"More than 7 episodes in last 24 hrs":"ಕಳೆದ 24 ಗಂಟೆಗಳಲ್ಲಿ 7 ಕ್ಕೂ ಹೆಚ್ಚು ಬಾರಿ",
	"Do you have any other medical conditions? *":"ನೀವು ಬೇರೆ ಯಾವುದೇ ವೈದ್ಯಕೀಯ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಹೊಂದಿದ್ದೀರಾ? *",
	"None":"ಯಾವುದೂ ಇಲ್ಲ",
	"High BP":"ಹೆಚ್ಚಿನ ಬಿಪಿ",
	"High BP + Diabetes Mellitus":"ಹೆಚ್ಚಿನ ಬಿಪಿ + ಮಧುಮೇಹ",
	"Reduced Immunity":"ರೋಗನಿರೋಧಕ ಶಕ್ತಿ ಕಡಿಮೆ ಇದೆ",
	"How is your health status in the last 48hrs? *":"ಕಳೆದ 48 ಗಂಟೆಗಳಲ್ಲಿ ನಿಮ್ಮ ಆರೋಗ್ಯ ಸ್ಥಿತಿ ಹೇಗಿದೆ? *",
	"Improved":"ಸುಧಾರಿತ",
	"No Change":"ಬದಲಾವಣೆ ಇಲ್ಲ",
	"Worsened":"ಹದಗೆಟ್ಟಿದೆ",
	"Worsened a lot":"ಬಹಳಷ್ಟು ಹದಗೆಟ್ಟಿದೆ",
	"Your age? *":"ನಿಮ್ಮ ವಯಸ್ಸು? *",
	"15 to 50 Yrs":"15 ರಿಂದ 50 ವರ್ಷಗಳು",
	"5 to 15 Yrs":"5 ರಿಂದ 15 ವರ್ಷಗಳು",
	"0 to 5 Yrs":"0 ರಿಂದ 5 ವರ್ಷಗಳು",
	"More than 50 Yrs":"50 ವರ್ಷಕ್ಕಿಂತ ಹೆಚ್ಚು",
	"Submit":"ಸಲ್ಲಿಸು",
	"HOME":"ಮನೆ",
	"You are safe, no need to worry":"ನೀವು ಸುರಕ್ಷಿತ, ಚಿಂತಿಸಬೇಕಾಗಿಲ್ಲ",
	"Exercise extreme caution and stay at home and notify medical authorities if condition deteriorates":"ತೀವ್ರ ಎಚ್ಚರಿಕೆ ವಹಿಸಿ ಮತ್ತು ಮನೆಯಲ್ಲಿಯೇ ಇರಿ ಮತ್ತು ಸ್ಥಿತಿ ಹದಗೆಟ್ಟರೆ ವೈದ್ಯಕೀಯ ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಿ",
	"Immediate medical attention is required and you may require COVID 19 testing":"ತಕ್ಷಣದ ವೈದ್ಯಕೀಯ ಆರೈಕೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ ಮತ್ತು ನಿಮಗೆ COVID 19 ಪರೀಕ್ಷೆಯ ಅಗತ್ಯವಿರುತ್ತದೆ"
  };